from flask import Flask, render_template, request
import re
import bcrypt
import hashlib
from pathlib import Path

app = Flask(__name__)

# Common weak passwords list
weak_passwords = ["password", "123456", "qwerty", "admin", "letmein"]

# Small bundled dictionary for the live/serverless demo.
# A hash cannot be mathematically converted back to its password; this
# feature checks candidate passwords and reports a match when one is found.
WORDLIST = Path(__file__).with_name("wordlist.txt")


# ------------ Password Strength Checker ------------
def password_strength(password):
    score = 0
    feedback = []

    if len(password) >= 8:
        score += 1
    else:
        feedback.append("Password should be at least 8 characters long.")

    if re.search(r"[A-Z]", password):
        score += 1
    else:
        feedback.append("Add at least one uppercase letter.")

    if re.search(r"[a-z]", password):
        score += 1
    else:
        feedback.append("Add at least one lowercase letter.")

    if re.search(r"[0-9]", password):
        score += 1
    else:
        feedback.append("Include at least one digit.")

    if re.search(r"[@$!%*?&]", password):
        score += 1
    else:
        feedback.append("Include at least one special character.")

    if password.lower() in weak_passwords:
        feedback.append("This is a very common password. Avoid it!")
        score = 1

    if score <= 2:
        strength = "Weak 🔴"
    elif score <= 4:
        strength = "Moderate 🟡"
    else:
        strength = "Strong 🟢"

    return strength, feedback


# ------------ Dictionary Hash Checker ------------
def load_candidates():
    try:
        with WORDLIST.open("r", encoding="utf-8") as f:
            return [line.strip() for line in f if line.strip()]
    except FileNotFoundError:
        return []


def crack_hash(target_hash):
    target_hash = target_hash.strip()
    candidates = load_candidates()

    if not candidates:
        return None, "Dictionary file is unavailable."

    # SHA-256 dictionary check
    if re.fullmatch(r"[0-9a-fA-F]{64}", target_hash):
        target = target_hash.lower()
        for candidate in candidates:
            if hashlib.sha256(candidate.encode()).hexdigest() == target:
                return candidate, "SHA-256 match found in the demo dictionary."
        return None, "No match found in the demo dictionary."

    # bcrypt dictionary check (for hashes generated by this app)
    if target_hash.startswith(("$2a$", "$2b$", "$2y$")):
        try:
            for candidate in candidates:
                if bcrypt.checkpw(candidate.encode(), target_hash.encode()):
                    return candidate, "Bcrypt match found in the demo dictionary."
        except ValueError:
            return None, "Invalid bcrypt hash."
        return None, "No match found in the demo dictionary."

    return None, "Unsupported hash format. Enter a SHA-256 or bcrypt hash."


# ------------ Flask Routes ------------
@app.route("/", methods=["GET", "POST"])
def index():
    result = None
    feedback = []
    hash_result = None
    cracked_password = None
    crack_message = None

    if request.method == "POST":
        password = request.form.get("password", "")
        hash_input = request.form.get("hash_input", "").strip()

        if password:
            strength, feedback = password_strength(password)
            sha256_hash = hashlib.sha256(password.encode()).hexdigest()
            bcrypt_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()

            result = strength
            hash_result = {"sha256": sha256_hash, "bcrypt": bcrypt_hash}

        elif hash_input:
            cracked_password, crack_message = crack_hash(hash_input)

    return render_template(
        "index.html",
        result=result,
        feedback=feedback,
        hash_result=hash_result,
        cracked_password=cracked_password,
        crack_message=crack_message,
    )


if __name__ == "__main__":
    app.run(debug=True)
